require 'rubygems'
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'rake/gempackagetask'
require 'date'

desc 'Default: run unit tests.'
task :default => :test

desc 'Test the machine.'
Rake::TestTask.new(:test) do |t|
  t.libs << 'lib'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

desc 'Generate documentation for the machine.'
Rake::RDocTask.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = 'rdoc'
  rdoc.title    = 'Machine'
  rdoc.options << '--line-numbers' << '--inline-source' << "--main" << "README.textile"
  rdoc.rdoc_files.include('README.textile')
  rdoc.rdoc_files.include('lib/**/*.rb')
end

spec = Gem::Specification.new do |s|
  s.name        = %q{machine}
  s.version     = "1.0.2"
  s.summary     = %q{machine defines a factory system for creating model objects to replace fixtures in Ruby apps.}
  s.description = %q{machine defines a factory system for creating model objects to replace fixtures in Ruby apps.}

  s.files        = FileList['[A-Z]*', 'lib/**/*.rb', 'test/**/*.rb']
  s.require_path = 'lib'
  s.test_files   = Dir[*['test/**/*_test.rb']]

  s.has_rdoc         = true
  s.extra_rdoc_files = ["README.textile"]
  s.rdoc_options = ['--line-numbers', '--inline-source', "--main", "README.textile"]

  s.authors = ["Aubrey Holland"]
  s.email   = %q{aubrey@patch.com}

  s.platform = Gem::Platform::RUBY
  s.add_dependency(%q<activesupport>, [">= 1.0"])
end

Rake::GemPackageTask.new spec do |pkg|
  pkg.need_tar = true
  pkg.need_zip = true
end

desc "Clean files generated by rake tasks"
task :clobber => [:clobber_rdoc, :clobber_package]

desc "Generate a gemspec file"
task :gemspec do
  File.open("#{spec.name}.gemspec", 'w') do |f|
    f.write spec.to_ruby
  end
end
